# Generated by Django 3.2.16 on 2022-12-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
