# Generated by Django 3.2.16 on 2022-12-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('achternaam', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefoonnummer', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('plaats', models.CharField(max_length=100)),
                ('land', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal', models.IntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='webshop.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('prijs', models.FloatField()),
                ('beschrijving', models.CharField(max_length=1000)),
                ('afbeelding', models.ImageField(upload_to='images/')),
                ('customer', models.ManyToManyField(related_name='producten', through='webshop.Order', to='webshop.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Verzekering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
                ('product', models.ManyToManyField(related_name='verzekeringen', to='webshop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='webshop.product'),
        ),
    ]
