# Generated by Django 3.2.16 on 2022-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nieuw',
            field=models.BooleanField(default=True),
        ),
    ]
