# Generated by Django 3.2.16 on 2022-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_product_nieuw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='achternaam',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='adres',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='land',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='naam',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='plaats',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='telefoonnummer',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='datum',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='afbeelding',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='naam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nieuw',
            new_name='new',
        ),
        migrations.RenameField(
            model_name='verzekering',
            old_name='naam',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='beschrijving',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prijs',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
