# Generated by Django 3.2.16 on 2022-12-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
