# Generated by Django 3.2.16 on 2022-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0002_cart_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
