# Generated by Django 3.2.16 on 2022-12-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_cartproduct_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='amount',
        ),
    ]
