# Generated by Django 3.2.16 on 2022-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_auto_20221215_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='aantal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
