# Generated by Django 3.2.16 on 2022-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='In behandeling', max_length=100),
        ),
    ]
