# Generated by Django 3.2.16 on 2022-12-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_alter_order_aantal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='aantal',
            new_name='amount',
        ),
    ]
