# Generated by Django 3.2.16 on 2022-12-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0005_auto_20221215_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In behandeling', 'In behandeling'), ('Verzonden', 'Verzonden'), ('Afgeleverd', 'Afgeleverd'), ('Geannuleerd', 'Geannuleerd')], default='In behandeling', max_length=100),
        ),
    ]
