# Generated by Django 3.2.21 on 2023-10-03 12:55

from django.db import migrations, models
import localflavor.nl.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phonenumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("postal_code", localflavor.nl.models.NLZipCodeField(max_length=7)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
            ],
        ),
    ]
