# Generated by Django 3.2.21 on 2023-10-10 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_orderproduct_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='order_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orderproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
    ]
