# Generated by Django 3.2.21 on 2024-07-03 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_auto_20240703_1549"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="created_at",
        ),
    ]
